name = "crawler"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[triggers]
crons = [
  "*/15 * * * *",
  "*/30 * * * *"
]

[build.upload]
rules = [
  { type = "Text", globs = ["**/*.txt"] }
]

[observability.logs]
enabled = false
invocation_logs = true
