name = "crawler"
main = "src/worker.js"
compatibility_date = "2025-12-01"

[[d1_databases]]
binding = "DB"
database_name = "crawler"
database_id = "3fdef111-2922-4149-af21-85de66f4a135"

[triggers]
crons = ["*/15 * * * *", "*/30 * * * *"]

[[rules]]
type = "Text"
globs = ["**/*.txt"]

[observability]
[observability.logs]
enabled = true
invocation_logs = true
